spring:
  application:
     name: service-proxy 
      
info:
  component: Zuul Server

server:
  port: 8080
  connection-timeout: 1000000
  compression:
    enabled: true  


ribbon: 
  ConnectTimeout: 30000
  ReadTimeout: 60000
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000        
zuul:
  routes:
    user:
      sensitiveHeaders:
      path: /user/**
      serviceId: service-user
      stripPrefix: true
    log:
      sensitiveHeaders:
      path: /log/**
      serviceId: service-logger
      stripPrefix: true
    msg:
      sensitiveHeaders:
      path: /msg/**
      serviceId: service-message
      stripPrefix: true

    auth:
      sensitiveHeaders:
      path: /auth/**
      serviceId: service-auth
      stripPrefix: true
  health:
    enabled: true
  add-proxy-headers: true
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000  
    max-total-connections: 10000
    max-per-route-connections: 10000
security:
    basic:
      enabled: false
      enable-csrf: false
      session: stateless 
        
eureka:
  instance:
    hostname: localhost
    port: 1111
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5 #Not in prod
    lease-expiration-duration-in-seconds: 5
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  

logging:
  level:
    ROOT: ERROR
    org.springframework.web: ERROR
  file: /log/${spring.application.name}.log

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false      