info:
  component: Authentication Service
         
# Spring properties
spring:
  application:
     name: service-auth 
  freemarker:
    enabled: false           
  datasource:
    name: mainDB # Name of the datasource.  
    password: toor 
    username: root
    url:  jdbc:mysql://localhost/ms?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false # JDBC url of the database.
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle : true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto : update
      dialect: org.hibernate.dialect.MySQL5Dialect
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  data:
   jpa:
    repositories:
     enabled: true
              
error:
  path: /error

logging:
  level:
    ROOT: ERROR
    org.springframework.web: ERROR
  file: /log/${spring.application.name}.log


# HTTP Server
server:
  port: 2200  
  compression:
    enabled: true  


#  port: ${random.int(2000,2010)}   # HTTP (Tomcat) port

eureka:
  instance:
    hostname: localhost
    port: 1111
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
      
#eureka:
#  instance:
#    hostname: localhost
#    port: 1111
    #leaseRenewalIntervalInSeconds: 5 
 # client:
 #   serviceUrl:
  #    defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
          
security:
  user:  none

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

#---
#spring:
#  profiles: prod2001

    
#    # HTTP Server
#server:
#  port: 2001   # HTTP (Tomcat) port

