spring:
  application:
    name: eureka
  profiles: default
  thymeleaf:
    enabled: false  
     
server:
  port: 1111 
    


eureka:
  instance:
    #preferIpAddress: true
    hostname: localhost
  server:
    enableSelfPreservation: true
    appname: MS-DEV_TEST
    eviction-interval-timer-in-ms: 1000   
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
   # serviceUrl:
   #   defaultZone: http://localhost:1111/eureka/   


# Configure this Discovery Server
#eureka:
#  instance:
#    hostname: localhost
#  client:  # Not a client, don't register with yourself
#    registerWithEureka: false
#    fetchRegistry: false

#logging:
#  level
#    ROOT: DEBUG
#    org.springframework.web: DEBUG
#  file: /log/${spring.application.name}.log
  

---

spring:
  profiles: production
        
server:
  port: 2222 

# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false

