#APP Security Token
app:
  token:
    url: http://localhost:8080/auth/oauth/check_token
    enable: true
    tokenfield: token
    PathPatterns: /**
     
# Spring properties
spring:
  application:
     name: service-message
  freemarker:
    enabled: false           
  datasource:
    name: mainDB   
    password: toor
    username: root
    url:  jdbc:mysql://localhost/ms?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false # JDBC url of the database.
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle : true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto : update
      dialect: org.hibernate.dialect.MySQL5Dialect
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:  
      hibernate.connection.charSet: UTF-8
  data:
   jpa:
    repositories:
     enabled: true
info:
  component: Message Service
          
error:
  path: /error


# HTTP Server
server:
  port: 2400   # HTTP (Tomcat) port
  compression:
    enabled: true  


  

eureka:
  instance:
    hostname: localhost
    port: 1111
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

logging:
  level:
    ROOT: ERROR
    org.springframework.web: ERROR
  file: /log/${spring.application.name}.log

---
spring:
  profiles: prod2001

    
    # HTTP Server
server:
  port: 2001   # HTTP (Tomcat) port

